# Generated by Django 4.1.7 on 2023-02-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="id",),
        migrations.RemoveField(model_name="menu", name="id",),
        migrations.AlterField(
            model_name="booking",
            name="ID",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name=11
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="ID",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name=5
            ),
        ),
    ]
