# Generated by Django 4.1.7 on 2023-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="menu", name="inventory", field=models.IntegerField(blank=True),
        ),
    ]
