# Generated by Django 4.1.7 on 2023-02-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0002_remove_booking_id_remove_menu_id_alter_booking_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="booking_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.booking",
            ),
        ),
    ]
