# Generated by Django 4.1.7 on 2023-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_menu_booking_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="ID",),
        migrations.RemoveField(model_name="menu", name="ID",),
        migrations.RemoveField(model_name="menu", name="booking_id",),
        migrations.AddField(
            model_name="booking",
            name="booking_id",
            field=models.IntegerField(
                default=None, max_length=11, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_id",
            field=models.IntegerField(
                default=None, max_length=5, primary_key=True, serialize=False
            ),
        ),
    ]
