# Generated by Django 4.1.7 on 2023-02-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_booking_booking_id_alter_menu_menu_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="booking_id", new_name="id",
        ),
        migrations.RenameField(model_name="menu", old_name="menu_id", new_name="id",),
    ]
