# Generated by Django 4.1.7 on 2023-02-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_rename_booking_id_booking_id_rename_menu_id_menu_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.AutoField(
                db_column="booking_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.AutoField(
                db_column="menu_id", primary_key=True, serialize=False
            ),
        ),
    ]
