# Generated by Django 4.1.7 on 2023-02-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_alter_booking_id_alter_menu_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="id", new_name="booking_id",
        ),
        migrations.RenameField(model_name="menu", old_name="id", new_name="menu_id",),
    ]
